title: Ashraf Ayman Alsalhi  # You can add your name here

description: Highly motivated, Self-Taught developer seeking to launch a career building mobile application using Flutter . # Fix hyphenation 

show_downloads: true # Fix spelling

theme: jekyll-theme-minimal 

plugins:
  - jekyll-seo-tag # Add SEO plugin

email: ashrafaymanalsalhi@gmail.com # Allow visitors to contact you
