name: business
description: A new Flutter project.
version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3

  # Utils
  get: ^4.3.7

  # State Management
  flutter_riverpod: ^0.14.0+3

  # OTP
  pin_code_fields: ^7.3.0

  # photo
  cached_network_image: ^3.1.0

  #  to comment view
  sliding_up_panel: ^2.0.0+1

  # for custom icons
  font_awesome_flutter: ^9.1.0

  # for drawer
  drawerbehavior: ^2.2.1

  # badges for profile image
  badges: ^2.0.1

  # to shimmer effect watting
  shimmer: ^2.0.0


  device_preview: ^0.7.4
  splash_screen_view: ^3.0.0

  # Save User Data
  shared_preferences: ^2.0.6
  path_provider: ^2.0.2

  #Get birth date picker
  flutter_datetime_picker: ^1.5.1


  #To upload image
  mime: ^1.0.0


  dio: ^4.0.0


  #  For read lattie animations
  lottie: ^1.1.0
  fluttertoast: ^8.0.8

  # TO MAKE PHONE CALL
  url_launcher: ^6.0.9

  # to delivery company
  expandable: ^5.0.1


  # Dotted Border
  dotted_border: ^2.0.0+1
  #  Get Image from phone
  image_picker: ^0.8.4+2
  file_picker: ^4.1.3

  flutter_reaction_button: ^1.0.8

  #  Upload File
  path: ^1.8.0

  #  Grid View
  flutter_staggered_grid_view: ^0.4.0


  audioplayers: ^0.20.1

  flutter_screenutil: ^5.0.0+2

  #Firebase
  firebase_core: ^1.7.0
  firebase_auth: ^3.1.2
  firebase_dynamic_links: ^2.0.10
  firebase_messaging: ^10.0.8
  cloud_firestore: ^2.5.3

  #  To get chat time
  timeago: ^3.1.0

  story_view: ^0.13.1

  connectivity: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

analyzer:
  enable-experiment:
    - non-nullable



# Icons android ios
# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"


# flutter pub run splash_screen_view:create
# flutter pub run splash_screen_view:remove
splash_screen_view:
  background_image: "assets/images/logo.png"

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/personView/
    - assets/images/bottomnav/
    - assets/images/drawer/
    - assets/images/chat/
    - assets/images/reacts/
    - assets/fonats/


  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonats/cairo.ttf
