import 'package:business/widget/custom_text.dart';
import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';

class CustomImage extends Container {
  CustomImage(String path,
      {text,
      key,
      bundle,
      frameBuilder,
      errorBuilder,
      semanticLabel,
      excludeFromSemantics = false,
      scale,
      width,
      height,
      color,
      colorBlendMode,
      fit,
      alignment = Alignment.center,
      repeat = ImageRepeat.noRepeat,
      centerSlice,
      matchTextDirection = false,
      gaplessPlayback = false,
      isAntiAlias = false,
      package,
      filterQuality = FilterQuality.low,
      cacheWidth,
      cacheHeight,
      EdgeInsetsGeometry? margin,
      EdgeInsetsGeometry? padding,
      String? title,
      double? verticalGap,
      double? fontSize,
      Color? titleColor,
      MainAxisAlignment? imageAndTitleAlignment,
      bool upperShadow = false})
      : super(
            margin: margin,
            padding: padding,
            child: Stack(
              children: [
                Column(
                  mainAxisAlignment:
                      imageAndTitleAlignment ?? MainAxisAlignment.center,
                  children: [
                    Image.asset(
                      path,
                      bundle: bundle,
                      cacheHeight: cacheHeight,
                      cacheWidth: cacheWidth,
                      package: package,
                      scale: scale,
                      key: key,
                      frameBuilder: frameBuilder,
                      errorBuilder: errorBuilder,
                      semanticLabel: semanticLabel,
                      excludeFromSemantics: excludeFromSemantics,
                      width: width,
                      height: height,
                      color: color,
                      colorBlendMode: colorBlendMode,
                      fit: fit,
                      alignment: alignment,
                      repeat: repeat,
                      centerSlice: centerSlice,
                      matchTextDirection: matchTextDirection,
                      gaplessPlayback: gaplessPlayback,
                      isAntiAlias: isAntiAlias,
                      filterQuality: filterQuality,
                    ),
                    if (title != null) SizedBox(height: verticalGap ?? 8.h),
                    if (title != null)
                      CustomText(
                        text: title,
                        fontSize: fontSize ?? 14.0.sp,
                        color: titleColor ?? const Color(0xff666666),
                      )
                  ],
                ),
                if (upperShadow)
                  Container(
                    height: 400.h,
                    decoration: BoxDecoration(
                      gradient: const LinearGradient(
                        colors: [Color(0xde000000), Color(0x00000000)],
                        stops: [0, 1],
                        begin: Alignment.topCenter,
                        end: Alignment.center,
                      ),
                    ),
                  )
              ],
            ));

  CustomImage.s1(String path,
      {Color? color,
      BoxFit? fit,
      MainAxisAlignment? imageAndTitleAlignment,
      bool upperShadow = false,
      EdgeInsetsGeometry? margin,
      EdgeInsetsGeometry? padding,
      String? title,
      double? verticalGap,
      double? fontSize,
      Color? titleColor})
      : this(path,
            imageAndTitleAlignment: imageAndTitleAlignment,
            height: 95.sp,
            width: 95.sp,
            color: color,
            upperShadow: upperShadow,
            padding: padding,
            margin: margin,
            title: title,
            verticalGap: verticalGap,
            fontSize: fontSize,
            titleColor: titleColor);

  CustomImage.s2(String path,
      {Color? color,
      BoxFit? fit,
      MainAxisAlignment? imageAndTitleAlignment,
      bool upperShadow = false,
      EdgeInsetsGeometry? margin,
      EdgeInsetsGeometry? padding,
      String? title,
      double? verticalGap,
      double? fontSize,
      Color? titleColor})
      : this(path,
            imageAndTitleAlignment: imageAndTitleAlignment,
            height: 70.sp,
            width: 70.sp,
            color: color,
            upperShadow: upperShadow,
            padding: padding,
            margin: margin,
            title: title,
            verticalGap: verticalGap,
            fontSize: fontSize,
            titleColor: titleColor);

  CustomImage.s3(String path,
      {Color? color,
      BoxFit? fit,
      MainAxisAlignment? imageAndTitleAlignment,
      bool upperShadow = false,
      EdgeInsetsGeometry? margin,
      EdgeInsetsGeometry? padding,
      String? title,
      double? verticalGap,
      double? fontSize,
      Color? titleColor})
      : this(path,
            imageAndTitleAlignment: imageAndTitleAlignment,
            height: 48.sp,
            width: 48.sp,
            color: color,
            upperShadow: upperShadow,
            padding: padding,
            margin: margin,
            title: title,
            verticalGap: verticalGap,
            fontSize: fontSize,
            titleColor: titleColor);

  CustomImage.s4(String path,
      {Color? color,
      BoxFit? fit,
      MainAxisAlignment? imageAndTitleAlignment,
      bool upperShadow = false,
      EdgeInsetsGeometry? margin,
      EdgeInsetsGeometry? padding,
      String? title,
      double? verticalGap,
      double? fontSize,
      Color? titleColor})
      : this(path,
            imageAndTitleAlignment: imageAndTitleAlignment,
            height: 32.sp,
            width: 32.sp,
            color: color,
            upperShadow: upperShadow,
            padding: padding,
            margin: margin,
            title: title,
            verticalGap: verticalGap,
            fontSize: fontSize,
            titleColor: titleColor);

  CustomImage.s5(String path,
      {Color? color,
      BoxFit? fit,
      MainAxisAlignment? imageAndTitleAlignment,
      bool upperShadow = false,
      EdgeInsetsGeometry? margin,
      EdgeInsetsGeometry? padding,
      String? title,
      double? verticalGap,
      double? fontSize,
      Color? titleColor})
      : this(path,
            imageAndTitleAlignment: imageAndTitleAlignment,
            height: 24.sp,
            width: 24.sp,
            color: color,
            upperShadow: upperShadow,
            padding: padding,
            margin: margin,
            title: title,
            verticalGap: verticalGap,
            fontSize: fontSize,
            titleColor: titleColor);

  CustomImage.s6(String path,
      {Color? color,
      BoxFit? fit,
      MainAxisAlignment? imageAndTitleAlignment,
      bool upperShadow = false,
      EdgeInsetsGeometry? margin,
      EdgeInsetsGeometry? padding,
      String? title,
      double? verticalGap,
      double? fontSize,
      Color? titleColor})
      : this(path,
            imageAndTitleAlignment: imageAndTitleAlignment,
            height: 12.sp,
            width: 12.sp,
            color: color,
            upperShadow: upperShadow,
            padding: padding,
            margin: margin,
            title: title,
            verticalGap: verticalGap,
            fontSize: fontSize,
            titleColor: titleColor);
}
